# Generated by Django 3.1.3 on 2020-12-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201129_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='uploads/teapot2.png', upload_to='avatar/%Y/%m/%d', verbose_name='avatar'),
        ),
    ]
